plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "com.modrinth.minotaur" version "2.+"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    runs {
        client {
            client()
            ideConfigGenerated = true

            configurations.mixinDependency.files.each {
                vmArg "-javaagent:$it.absolutePath".toString()
            }

            source sourceSets.main
        }
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }

    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury-fabric:${architectury_version}"

    modImplementation "com.simibubi.create:create-fabric-${create_minecraft_version}:${create_version}"
    /*modImplementation "com.jozufozu.flywheel:flywheel-fabric-${flywheel_minecraft_version}:${flywheel_version}"
    modImplementation "com.tterrag.registrate:Registrate:${registrate_version}"*/

    modApi("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    modApi "com.terraformersmc:modmenu:${mod_menu_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    inputs.properties version: project.version, mod_id: mod_id

    filesMatching("fabric.mod.json") {
        expand version: project.version, mod_id: mod_id
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = (project(":common") as Project).tasks.getByName("sourcesJar") as org.gradle.jvm.tasks.Jar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = archives_base_name + "-" + project.name
            from components.java
        }
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "create-train-perspective"
    versionName = "Create: Train Perspective v${mod_version} (Fabric/Quilt 1.20.1)"
    versionNumber = "${mod_version}+fabric-1.20.1"
    versionType = modrinth_version_type
    uploadFile = remapJar
    additionalFiles = [sourcesJar]
    gameVersions = [minecraft_version]
    loaders = ["fabric", "quilt"]
    changelog = rootProject.file("changelog.md").getText()

    dependencies {
        required.project 'fabric-api'
        required.project 'create-fabric'
        required.project 'architectury-api'
        optional.project 'cloth-config'
        optional.project 'modmenu'
    }
}
