architectury {
    common(enabled_platforms.split(","))
}

group = rootProject.group
version = rootProject.version

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury:${architectury_version}"

    modImplementation("maven.modrinth:create:${create_minecraft_version}-${create_version}") { transitive = false }

    modApi("me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}")
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }
}
